#pragma once

#include <utils/types.hpp>

namespace lexer {

    enum class TokenType : usize {
        Print,
        Println,
        LowercaseFunction,
        Colon,
        Comma,
        TildeArrow,
        EndOfFile,
        Semicolon,
        Plus,
        Minus,
        Asterisk,
        Mod,
        ForwardSlash,
        LeftParenthesis,
        RightParenthesis,
        LeftCurlyBracket,
        RightCurlyBracket,
        Let,
        Equals,
        SignedIntegerLiteral,
        UnsignedIntegerLiteral,
        CharLiteral,
        StringLiteral,
        BoolLiteral,
        And,
        Or,
        Not,
        If,
        Else,
        Loop,
        Break,
        Continue,
        While,
        Do,
        For,
        Mutable,
        Const,
        EqualsEquals,
        ExclamationEquals,
        GreaterThan,
        LessThan,
        GreaterOrEquals,
        LessOrEquals,
        Return,
        NothingLiteral,
        UppercaseFunction,
        LineComment,
        Whitespace,
        LowercaseIdentifier,
        UppercaseIdentifier,
    };

} // namespace lexer
